### ISSUE TITLE
add face editing demo to colab

### ISSUE THREAD

**Issue by AK391** [mit-han-lab/anycost-gan#10]
is it possible to add the face editing demo to the colab notebook? Thanks

**Comment by Adeel-Intizar** [comment]
It would be great if a face editing demo as shown in a video with slider controls is provided, it'll help everyone and it'll be much appreciated

**Comment by tonylins** [comment]
> It would be great if a face editing demo as shown in a video with slider controls is provided, it'll help everyone and it'll be much appreciated

Hi, we already provided the demo code in this repo. Please find more information here: https://github.com/mit-han-lab/anycost-gan#interactive-demo. Thanks!
