### ISSUE TITLE
checkpoint for mult-resolution training 

### ISSUE THREAD

**Issue by betterze** [mit-han-lab/anycost-gan#17]
Dear anycost-gan team,

Thank you for sharing this great work, I really like it. 

Would you minding sharing the intermedia checkpoint for mult-resolution step? To train anycost gan, we need to do 3 steps:

1. Training the original StyleGAN2 on FFHQ
2. Training Anycost GAN: mult-resolution
3. Training Anycost GAN: adaptive-channel

You provide the checkpoint for 1st and 3rd steps. Would you minding aslo sharing the checkpoint for the second step? I understand that I can train it by myself, but 8 gpus for 5 days is really too heave resource for us. 

Thank you for your help.

Best Wishes,

Alex

**Comment by tonylins** [comment]
Hi Alex, 

Thanks for your interest in our work. You may find the checkpoint for the multi-resolution model here: https://hanlab.mit.edu/projects/anycost-gan/files/generator_multires-ffhq-config-f.pth.

Best,
Ji

**Comment by betterze** [comment]
thx a lot. I really appreciate it.

**Comment by betterze** [comment]
I am sorry to bother you again. [ The multi-resolution model](https://hanlab.mit.edu/projects/anycost-gan/files/generator_multires-ffhq-config-f.pth.) seems to only contain generator but not discriminator, would you may share both G and D? 

Thank you again for your help. I really appreciate it.

**Comment by betterze** [comment]
thx a lot.
