### ISSUE TITLE
About Adaptive-channel training and Generator-conditioned discriminator.

### ISSUE THREAD

**Issue by GreenLimeSia** [mit-han-lab/anycost-gan#2]
Dear Mit-han-lab:

Thank you very much for sharing your excellent work.

I have two questions regarding the code: 1) For the Step Adaptive-channel training source code, where can I find it? Is dynamic_channel.py required for this process? Whether Is it included in the unpublished train.py? 2) I do not find G_arch operations in class Generator and DiscriminatorMultiRes.

Would you kindly help me answer this question in your spare time?

Best Wishes,

GreenLimeSia

**Comment by tonylins** [comment]
Hi GreenLimeSia,

The adaptive channel and conditioned discriminator parts are included in the training part. We will update the training code shortly after a proper clean-up. Stay tuned!

Best,
Ji

**Comment by GreenLimeSia** [comment]
Many thanks for your reply.We are looking forward to your update train file.
Thanks again.
