### ISSUE TITLE
in extract_edit_directions.py 

### ISSUE THREAD

**Issue by Winnie202** [mit-han-lab/anycost-gan#21]
Hi，I am very confused，Attribute-predictor is poorly explained，How do I get an Attribute-predictor .pt file on different datasets？

**Comment by tonylins** [comment]
Hi, for the face-related dataset (e.g., FFHQ), we have a supervised dataset CelebA (https://mmlab.ie.cuhk.edu.hk/projects/CelebA.html), which contains face images and associated labels (e.g., is smiling, is wearing sunglasses, etc.). We used the dataset to train an attribute predictor.

For other datasets, you can find similar labeled data to train the predictor.
