### ISSUE TITLE
using win run demo.py need cuda but cant using force-native=1

### ISSUE THREAD

**Issue by fingerx** [mit-han-lab/anycost-gan#22]
hi,thanks for job. my win10 pc run stylegan3 is ok but run anycost-gan , demo.py need cuda, using force-native=1, my pc cant understand,anyone can help me,thanks very much.

**Comment by fingerx** [comment]
thanks
![image](https://user-images.githubusercontent.com/5524551/158086976-1badc78c-0b08-4591-bf00-20b686185e0b.png)

**Comment by fingerx** [comment]
yes  my pc is nv 3080 gpu
![image](https://user-images.githubusercontent.com/5524551/158549891-ab18ab4f-5740-4072-81ce-f45aef085356.png)

**Comment by fingerx** [comment]
run stylegan3 is ok:
![Uploading image.png…]()

**Comment by tonylins** [comment]
Thanks. I don't have too much experience with Windows. But could you please try:
```
set FORCE_NATIVE=1
python demo. py
```

**Comment by fingerx** [comment]
ok thanks

**Comment by fingerx** [comment]
dont know why that,but thanks for you
