### ISSUE TITLE
Could you please provide pre-trained boundaries of 'stylegan2-ffhq-config-f'?

### ISSUE THREAD

**Issue by yuxu915** [mit-han-lab/anycost-gan#24]
Hi, thanks for your brilliant work!
However when I try to get pre-trained directions, it seems these pre-trained boundaries are missing.
For example, I cannot find the webpage 'https://hanlab.mit.edu/projects/anycost-gan/files/boundary_stylegan2-ffhq-config-f'.
Could you please fix this problem or share the boundary files with me?
That would be great help.
Thank you very much.

**Comment by tonylins** [comment]
Hi, you are missing the `.pt` suffix for the URL. You can try `wget //hanlab.mit.edu/projects/anycost-gan/files/boundary_stylegan2-ffhq-config-f.pt`. 

Please refer to the `URL_TEMPLATE` variable here: https://github.com/mit-han-lab/anycost-gan/blob/1177beafaf5ed486156f78f411c34e62f0d46f14/models/__init__.py#L6
