### ISSUE TITLE
关于encoder的训练

### ISSUE THREAD

**Issue by zhaoyk1986** [mit-han-lab/anycost-gan#3]
您好，感谢分享。
有一些不太理解的地方，希望能解答。

encoder, generator, discriminator的训练流程是怎样的？
         我猜测是 先discriminator, generator训练完成后， 使用generator来训练encoder。这种流程，encoder是不会影响generator。
那么是否可以三个模型一起训练。互相影响，达到最优。

**Comment by tonylins** [comment]
Hi, we first jointly train the generator and discriminator (conventional GAN training), and then train the encoder for the fixed generator. Co-optimizing D, G, and E may bring some benefits, but it is beyond the scope of our paper.

Best,
Ji

**Comment by tonylins** [comment]
I will close the issue now due to inactivity. Feel free to reopen if you have other questions.
