### ISSUE TITLE
mean style requires cuda tensor but got ''cpu'' while runing demo.py

### ISSUE THREAD

**Issue by yian2271368** [mit-han-lab/anycost-gan#4]
https://github.com/mit-han-lab/anycost-gan/blob/19229bdc525ecd00ca7c2322b192504325bda9e0/models/anycost_gan.py#L85
here 'z' is "cpu" device while self.style needs "cuda" tensor???
Error is: RuntimeError: input must be a CUDA tensor
i figured out the reason is the code then running to FusedLeakyReLUFunction ,which requires CUDA tensor. But in demo.py, the device is "cpu". Any idea how to fix this problem?

**Comment by tonylins** [comment]
Hi, sorry about that. The demo was tested on a CPU-only machine, which fails to expose the problem. 

You can run the demo with `FORCE_NATIVE=1 python demo.py `

**Comment by yian2271368** [comment]
@tonylins thanks! It works！
BTW， what is this FORCCE_NATIVE=1 refers to ? is that means force to disable all GPUS?

**Comment by yian2271368** [comment]
thank you! that works!

**Comment by fingerx** [comment]
hi,want to know my pc cant understand FORCE_NATIVE=1. thanks 
but my pc run stylegan3 using cuda is ok

**Comment by fingerx** [comment]
@tonylins  need your help,thanks
