### ISSUE TITLE
 How can I edit my photos using your already trained model in demo.py

### ISSUE THREAD

**Issue by GewGaw74** [mit-han-lab/anycost-gan#6]
Hello. I express my gratitude for the work done.

I am far from programming. Installed your project.
Can you explain in more detail how I can edit my images using demo.py. I found the paths input_images and projected_latents. 
Npy files stay old when replacing images. 

What steps should I take to get interactive image editing for my images? 

Thanks in advance, I don’t know how to do it.

**Comment by tankhang2004** [comment]
Have you done it? If so, I need your help. It seems like this repo is generating faces out of randomness and edit those random faces. I want to upload my own images and edit them. How do I do that?
