### ISSUE TITLE
low-resolution output image looks unnatural

### ISSUE THREAD

**Issue by BruceLeeeee** [mit-han-lab/anycost-gan#7]
I find low-resolution outputs image(below 128 size) looks unnatural.
According to Figure 4b, the low-resolution output should look natural too but is similar to vanilla StyleGAN2 output.

**Comment by tonylins** [comment]
Hi, as stated in the paper, we train our models to support four resolutions from the highest: in figure 4b (ablation study), the highest resolution is 256, so the resolution range is 32-256; For the released model, the highest resolution is 1024, so the resolution range is 128-1024.

We find that resolutions below 128 are too blurry for preview, which may not be very useful.
