### ISSUE TITLE
Is AnycostGAN effective in shortening the experiment time?

### ISSUE THREAD

**Issue by YoungJaeK** [mit-han-lab/anycost-gan#9]
Hi, @tonylins 
I have a question.
As I understand, this study has been studied for the purpose of fast inference in several edge devices.

In addition, this technology seems to be trying to effectively apply knowledge distillation to a high resolution that requires a lot of learning time by conducting various experiments with a fast experiment at low resolution and the confirmed experimental results.

In this part, I am interested. I want to do sufficiently different experiments (ex. Conditional GAN ​​etc.) at 64x64 or 128x128 using AnycostGAN, and apply it to high resolution after completing the experiment. I am curious if it will be applied well to this part.

Obviously, it will be confirmed by experimenting, but if there are any additional papers or techniques that can be referenced in this research method, I would appreciate it if you would recommend it.

And I am curious about your opinion on whether applying technology to high resolution after experimenting in low resolution for the fast experiment is more effective than learning single resolution.

**Comment by tonylins** [comment]
Hi, sorry for the late reply. That is an interesting question. For Anycost GANs, there are two dimensions: resolutions and channels. Actually the channel dimension is harder to support. 

If you are only interested in multi-resolution training, it can actually boost the FIDs and reduce training time to some extent (see Table 1), which means you can get better FIDs at shorter training time. I don't have a concrete acceleration number though.

I will close the issue for now. Feel free to follow up with the discussion!
